name: Update flat jobs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *' # Run at 18:00 each day


jobs:
  update-flat-jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Update
      run: bundle exec rake update
    - name: Push changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Update ($(date "+%Y-%m-%d"))" || exit 0
        git push
